### PR TITLE
Update ecobee-connect.groovy

### PR DESCRIPTION
**Pull request by snakedog116**
Added a 'Other Preferences' page (for future use), currently it has a 'success' message.

Re-entered the license info

### CODE REVIEW

**Comment by StrykerSKS** [comment]
Won't the license be added once this is merged upstream? I didn't delete the license text, I think my branch just started before they merged in your license pull request.

Do you think the "Success" page is needed for a general user? For "advanced" users I know some people get frustrating with extra steps if they aren't needed, so was trying to avoid having extraneous bits. 

I have some more "advanced" features in the current development branch under this one that I could move to this page I suppose.

**Comment by snakedog116** [comment]
Yea it might. 

Have you started a pull request?

You seem to have a lot of versions going on. :)

**Comment by StrykerSKS** [comment]
I've synced up with the upstream now which has pulled in the license file.

I'm actually only maintaining two different branches now: 1) StrykerSKS-Ecobee3 and 2)  StrykerSKS-enhanced-ecobeedevice. The first one is intended to be the more stable branch, while the second branch will be for my working copy where I'll be making checkpoints as I go. 

I just rolled a BIG update back into the Ecobee3 branch which is what I'll publish on the community site as soon as I finish writing up some instructions.

**Comment by StrykerSKS** [comment]
Gonna close this one out. Try updating to the new version and let me know what you think.

**Pull request closed without merging**
